---
version: '3.7'
services:
  app:
    image: dm-dev:latest
    build:
      args:
        USERNAME: ${USER}
        DM_DEV_EXCLUDE: "dm-dev dm-tags dm-ar-finders" # Makes sure that these gems are not used
        DM_DEV_INCLUDE: "dm-core data_mapper dm-aggregates dm-constraints dm-do-adapter dm-migrations dm-mysql-adapter dm-noisy-failures dm-serializer dm-timestamps dm-transactions dm-types dm-validations"
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DM_DEV_ROOT: "/home/${USER}/datamapper" # Points to where the DM sources will be installed and used
      DO_MYSQL_USER: datamapper
      DO_MYSQL_PASS: datamapper
      DO_MYSQL_HOST: mysql
      DM_DB_HOST: mysql
      USER: ${USER}
    volumes:
      - ~/.ssh:/home/${USER}/.ssh
      - ../dotfiles/.history:/var/www/.history:delegated
      - .:/home/$USER/datamapper/dm-dev:delegated
      - ../data_mapper:/home/$USER/datamapper/data_mapper:delegated
      - ../datamapper-do:/home/$USER/datamapper/datamapper-do:delegated
      - ../dm-aggregates:/home/$USER/datamapper/dm-aggregates:delegated
      - ../dm-constraints:/home/$USER/datamapper/dm-constraints:delegated
      - ../dm-core:/home/$USER/datamapper/dm-core:delegated
      - ../dm-do-adapter:/home/$USER/datamapper/dm-do-adapter:delegated
      - ../dm-migrations:/home/$USER/datamapper/dm-migrations:delegated
      - ../dm-mysql-adapter:/home/$USER/datamapper/dm-mysql-adapter:delegated
      - ../dm-noisy-failures:/home/$USER/datamapper/dm-noisy-failures:delegated
      - ../dm-serializer:/home/$USER/datamapper/dm-serializer:delegated
      - ../dm-timestamps:/home/$USER/datamapper/dm-timestamps:delegated
      - ../dm-transactions:/home/$USER/datamapper/dm-transactions:delegated
      - ../dm-types:/home/$USER/datamapper/dm-types:delegated
      - ../dm-validations:/home/$USER/datamapper/dm-validations:delegated
    networks:
      default:
        aliases:
          - dm.sbf.engineering
  mysql:
    image: mysql:8.0
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      HISTFILE: var/www/.history/bash
      MYSQL_RANDOM_ROOT_PASSWORD: 1

volumes:
  mysql-data:
